# Generated by Django 3.0.2 on 2021-07-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('bitcoin', 'bitcoin'), ('cardano', 'cardano'), ('dogecoin', 'dogecoin'), ('ethereum', 'ethereum'), ('monero', 'monero'), ('polkadot', 'polkadot')], default='bitcoin', max_length=12)),
                ('payment_id', models.CharField(max_length=6)),
                ('wallet_address', models.TextField(null=True)),
                ('amount_received', models.FloatField(null=True)),
                ('tx_ids', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
