# Generated by Django 3.0.2 on 2021-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='raw_tx_data',
            field=models.TextField(null=True),
        ),
    ]
