# Generated by Django 3.0.2 on 2021-07-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_processor', '0003_payment_monero_account_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ethereum_account_password',
            field=models.CharField(default='', max_length=36),
        ),
    ]
